import numpy as np
import npragglib as lib
import sim
import npragglib as npr
import numpy as np

X = np.matrix(" 10; 0; 0; 0")
Y = np.matrix("1, 0, 0, 0;"
              "0, 0, 0, 0;"
              "0, 0, 0, 0;"
              "1, 0, 0, 0;"
              "1, 1, 1, 1")

# M number of data points
# K number of agents
# d dimension of features
# X numpy array with shape (M, dim), which is the feature vector
# Y binary (including labels, only 0 or 1) numpy array of shape (K, M), which is the matrix of all labels generated by all K models for all M samples

# The following function will give the estimated labels
Z_est = lib.em(X=, Y=, K=, M=,)
